import './globals.css';

export const metadata = {
    title: 'WEB tutotials',
    description: 'Generated by yujin',
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>
                <h1>
                    <a href="/">WEB</a>
                </h1>
                <ol>
                    <li>
                        <a href="read/1">html</a>
                    </li>
                    <li>
                        <a href="rea/2">css</a>
                    </li>
                </ol>
                {children}
                <ul>
                    <li>
                        <a href="/create">Create</a>
                    </li>
                    <li>
                        <a href="/update/1">Update</a>
                    </li>
                    <li>
                        <input type="button" value="Delete"></input>
                    </li>
                </ul>
            </body>
        </html>
    );
}
